import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Work from "@/components/Work";
import About from "@/components/About";
import Testimonial from "@/components/Testimonial";
import ClientLogo from "@/components/ClientLogo";
import Project from "@/components/Project";
import Counter from "@/components/Counter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Interior Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Banner />
        <Work />
        <About />
        <Testimonial />
        <ClientLogo />
        <Project />
        <Counter />
      </main>
    </>
  );
}
